### ISSUE TITLE
No Start of Harry Plotter after a pt-get update/upgrade

### ISSUE THREAD

**Issue by blaupert** [abueide/harry-plotter#41]
1.1.6-1 dont start its gui anymore 
I did a apt-get update/Upgrade on my Ubuntu 20.04
Even deleted the ~/.java ... no gui start anymore. The request Window for chia executable came ... i did the choice... but nothing else happens!

Uninstall/re-installed the .deb ... nothing :(

Cant start it!

**Comment by abueide** [comment]
Hi, could you run this command in the terminal and paste the output?

`/opt/harry-plotter-setup/bin/Harry\ Plotter'

thanks

**Comment by blaupert** [comment]
Sure:

~$ /opt/harry-plotter-setup/bin/Harry\ Plotter
May 25, 2021 8:28:38 PM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @136a0e4'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:903)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the array '[', but had 'EOF' instead
JSON input: 
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
    at kotlinx.serialization.json.internal.JsonLexer.fail(JsonLexer.kt:477)
    at kotlinx.serialization.json.internal.JsonLexer.fail(JsonLexer.kt:215)
    at kotlinx.serialization.json.internal.JsonLexer.unexpectedToken(JsonLexer.kt:198)
    at kotlinx.serialization.json.internal.JsonLexer.consumeNextToken(JsonLexer.kt:190)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:37)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
    at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
    at com.abysl.harryplotter.config.Config.getPlotJobs(Config.kt:71)
    at com.abysl.harryplotter.viewmodel.MainViewModel.<init>(MainViewModel.kt:41)
    at com.abysl.harryplotter.view.MainView.initialized(MainView.kt:58)
    at com.abysl.harryplotter.HarryPlotter.start(HarryPlotter.kt:43)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:849)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    ... 1 more
Failed to launch JVM

**Comment by blaupert** [comment]
Did a Java jre Version check
![20210525_203427.jpg](https://user-images.githubusercontent.com/47336322/119550435-b38d6980-bd98-11eb-95ed-07e3c4986511.jpg)

**Comment by abueide** [comment]
try deleting the ~/.harryplotter folder (this will make you lose your stats & plot jobs)

**Comment by blaupert** [comment]
Yes! Brought back the gui.
All settings are gone. But hey no prob!

**Comment by abueide** [comment]
Hi, my program doesn't  copy files or mess with your ssd at all. It simply passes in the destination path to the chia executable, so I don't think my program could do anything to crash it.

Sorry about the lost time, I'll try to improve the serialization in the future to autohandle bugs like this.
