### ISSUE TITLE
No keys on system, unable to start plots using keys manually entered through Harry Plotter

### ISSUE THREAD

**Issue by Kiggles** [abueide/harry-plotter#77]
Software works when keys were present. Began experimenting with potentially more secure configurations for another system to be setup.

Secured mnemonics. Deleted chia keys. Manually entered public keys through Harry Plotter. Save. Start.

[14948] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 57, in create_plots
  File "chia\plotting\create_plots.py", line 30, in get_farmer_public_key
RuntimeError: No keys, please run 'chia keys add', 'chia keys generate' or provide a public key with -f

Triple, and, Quadruple checked public keys entered through Harry Plotter.

I assume this is a symptom of chia.exe complaining about absence of any stored keys. Is this a non-issue and Chia.net supplied commandline plotters simply need keys on the system (even if throw away)? 

Thanks!

**Comment by abueide** [comment]
Hi,

I suspect this is a bug in harry plotter. I'll do some more testing & try to make sure its working well for the 1.1.12 release coming soon.

**Comment by Kiggles** [comment]
Version 1.1.11

![Capture1](https://user-images.githubusercontent.com/58374442/120303381-c8886200-c29c-11eb-9f16-b5bb7c5bbf34.JPG)

**Comment by abueide** [comment]
@Kiggles I fixed the bug in 1.1.12. for now you can  get it to work by removing the fingerprint from the key.

**Comment by Kiggles** [comment]
Thanks! Had to regenerate a new key entry but that did the trick.

**Comment by abueide** [comment]
fixed in 1.1.12
